baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "main"
defaultContentLanguageInSubdir = true
theme = "terminal"
paginate = 5


[markup.goldmark.renderer]
smartypants = false
unsafe = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.main]
    themeColor = "blue"
    contentDir = "content/main"
    languageName = "Chinese"
    title = "Beyond Moonlight"
    subtitle = ""
    owner = "Tsukimaru Oshawott"
    keywords = ""
    copyright = ""
    menuMore = "显示更多"
    readMore = "阅读全文"
    readOtherPosts = "阅读其他文章"
    newerPosts = "上一页"
    olderPosts = "下一页"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "返回主页"

    [languages.main.params.logo]
      logoText = "cutekibry@Tsukimaru"
      logoHomeLink = "/"

    [languages.main.menu]
      [[languages.main.menu.main]]
        identifier = "tags"
        name = "标签列表"
        url = "/main/tags/"

      [[languages.main.menu.main]]
        identifier = "feedback"
        name = "留言板"
        url = "/main/posts/feedback/"
        
  [languages.inner]
    themeColor = "red"
    contentDir = "content/inner"
    languageName = "Chinese"
    title = "The Dark Side of The Moon"
    subtitle = ""
    owner = "Tsukimaru Oshawott"
    keywords = ""
    copyright = ""
    menuMore = "显示更多"
    readMore = "阅读全文"
    readOtherPosts = "阅读其他文章"
    newerPosts = "上一页"
    olderPosts = "下一页"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "返回主页"

    [languages.inner.params.logo]
      logoText = "root@Tsukimaru"
      logoHomeLink = "/inner"

    [languages.inner.menu]
      [[languages.inner.menu.main]]
        identifier = "main"
        name = "返回表博客"
        url = "/main/"
      [[languages.inner.menu.main]]
        identifier = "tags"
        name = "标签列表"
        url = "/inner/tags/"
      [[languages.inner.menu.main]]
        identifier = "feedback"
        name = "留言板（里）"
        url = "/inner/posts/feedback/"